version: "3.7"

volumes:
  rstuf-api-data:
  rstuf-worker-data:
  rstuf-mq-data:
  rstuf-storage:
  rstuf-redis-data:
  rstuf-pgsql-data:

secrets:
  SECRETS_RSTUF_ADMIN_PASSWORD:
    external: True
  SECRETS_RSTUF_TOKEN_KEY:
    external: True
  SECRETS_RSTUF_ONLINE_KEY_PASSWORD:
    external: True
  # HTTPS (SSL)
  # API_KEY:
  #   external: True
  # API_CRT:
  #   external: True

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    volumes:
      - "rstuf-mq-data:/var/lib/rabbitmq"
    healthcheck:
      test: "exit 0"
    restart: always
    tty: true

  redis:
    image: redis:4.0
    volumes:
      - rstuf-redis-data:/data
    healthcheck:
      test: "exit 0"
    restart: always
    tty: true

  postgres:
    image: postgres:15.1
    ports:
      - "5433:5432"
    # DO NOT USE IT IN PRODUCTION. Check the Postgres best practices
    environment:
      - POSTGRES_PASSWORD=secret
    volumes:
      - "rstuf-pgsql-data:/var/lib/postgresql/data"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "postgres"]
      interval: 1s

  rstuf-worker:
    image: ghcr.io/vmware/repository-service-tuf-worker:latest
    volumes:
      - rstuf-worker-data:/data
      - rstuf-storage:/var/opt/repository-service-tuf/storage
      - ./local-keyvault/:/var/opt/repository-service-tuf/keyvault/ # map the path where is your keys
    environment:
      RSTUF_STORAGE_BACKEND: LocalStorage
      RSTUF_KEYVAULT_BACKEND: LocalKeyVault
      RSTUF_LOCAL_STORAGE_BACKEND_PATH: /var/opt/repository-service-tuf/storage
      RSTUF_LOCAL_KEYVAULT_PATH: /var/opt/repository-service-tuf/keyvault/online.key
      RSTUF_LOCAL_KEYVAULT_PASSWORD: /run/secrets/SECRETS_RSTUF_ONLINE_KEY_PASSWORD
      RSTUF_BROKER_SERVER: amqp://guest:guest@rabbitmq:5672
      RSTUF_REDIS_SERVER: redis://redis
      RSTUF_SQL_SERVER: postgresql://postgres:secret@postgres:5432
      RSTUF_WORKER_ID: rstuf_worker_001
    secrets:
      - SECRETS_RSTUF_ONLINE_KEY_PASSWORD
    depends_on:
      - redis
      - rabbitmq
    healthcheck:
      test: "exit 0"
    restart: always
    tty: true

  web-server:
    image: python:3.10-slim-buster
    command: python -m http.server -d /www 8080
    volumes:
      - rstuf-storage:/www
    ports:
      - "8080:8080"

  rstuf-api:
    image: ghcr.io/vmware/repository-service-tuf-api:latest
    volumes:
      - rstuf-api-data:/data
    ports:
      - 80:80
      - 443:443
    environment:
      RSTUF_BOOTSTRAP_NODE: "true"
      RSTUF_BROKER_SERVER: amqp://guest:guest@rabbitmq:5672
      RSTUF_REDIS_SERVER: redis://redis
      SECRETS_RSTUF_TOKEN_KEY: /run/secrets/SECRETS_RSTUF_TOKEN_KEY
      SECRETS_RSTUF_ADMIN_PASSWORD: /run/secrets/SECRETS_RSTUF_ADMIN_PASSWORD
      # HTTP (SSL)
      # SECRETS_RSTUF_SSL_CERT: /run/secrets/API_CRT
      # SECRETS_RSTUF_SSL_KEY: /run/secrets/API_KEY
    secrets:
      - SECRETS_RSTUF_ADMIN_PASSWORD
      - SECRETS_RSTUF_TOKEN_KEY
      - SECRETS_RSTUF_ONLINE_KEY_PASSWORD
      # HTTPS (SSL)
      # - API_CRT
      # - API_KEY
    depends_on:
      - rabbitmq
      - redis
      - rstuf-worker
