name: CI

on:
  push:
    branches: [ 'main' ]
    paths:
      - 'tests/**'
      - 'requirements.txt'
      - '.github/workflows/functional.yml'
      - '.github/workflows/ci.yml'
  pull_request:
    branches: [ 'main' ]
    paths:
      - 'tests/**'
      - 'requirements.txt'
      - '.github/workflows/functional.yml'
      - '.github/workflows/ci.yml'
  workflow_dispatch:

jobs:
  functional-tests:
    uses: ./.github/workflows/functional.yml
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    with:
      api_version: dev
      worker_version: dev
      cli_version: dev
