name: readthedocs/actions
on:
  pull_request_target:
    types:
      - opened
    paths:
      - "docs/**"
      - "TAC.rst"
      - "CONTRIBUTING.rst"
      - "CODE_OF_CONDUCT.rst"
      - "LICENSE"
      - "MAINTAINERS.rst"
      - "README.rst"
      - "ROADMAP.rst"

permissions:
  pull-requests: write

jobs:
  pull-request-links:
    runs-on: ubuntu-latest
    steps:
      - uses: readthedocs/actions/preview@v1
        with:
          project-slug: "repository-service-tuf"